# Generated by Django 6.0 on 2025-12-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_group_options_alter_group_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.tutor'),
            preserve_default=False,
        ),
    ]
